spring.application.name=StudySpring
##Eclipseでの開発時に新たに追加した項目

##以下を記入することで個々人のローカル環境に合わせて、その都度、対応できるようになる
server.port=${PORT:8080}

# Spring Bootの設定ファイルに記述する「H2データベースの接続設定」
spring.datasource.url=jdbc:h2:file:./data/safety_check
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console