spring.application.name=StudySpring
##Eclipseでの開発時に新たに追加した項目

##以下を記入することで個々人のローカル環境に合わせて、その都度、対応できるようになる
server.port=${PORT:8080}

# Spring Bootの設定ファイルに記述する「H2データベースの接続設定」
spring.datasource.url=jdbc:h2:file:./data/safety_check
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

#Spring Boot + JPA + data.sql の組み合わせで実行しようとするとこれがないとダメらしい
#JPA（Hibernateなど）によるテーブル自動生成より後に、data.sql・schema.sqlの実行を遅らせる
#ymlの階層構造を活用してもいいかもしれない
spring.jpa.defer-datasource-initialization=true